use_frameworks!
platform :ios, '11.0'

target 'CrowdBoticsStarter' do
  pod 'crowdbotics', :path => '../'

  pod 'IQKeyboardManagerSwift'
  pod 'SideMenu'

  target 'crowdbotics_Tests' do
    inherit! :search_paths
    
  end
end
